<template>
  <v-container>
    <v-row>
      <v-col cols="12">
        <div class="text-center white--text">
          <h1>{{ this.content.title }}</h1>
        </div>
      </v-col>
    </v-row>
    <v-row class="d-flex justify-center">
      <v-col cols="12" md="4" class="d-flex justify-center">
        <v-img :src="require('@/assets/help/00000349.png')" class="" contain />
      </v-col>
    </v-row>
    <v-row class="pb-10 d-flex justify-center">
      <v-col col="12" md="8">
        <v-card
          v-for="i in this.help"
          :key="i.title"
          class="pa-4 mb-4 text-justify"
          width="100%"
          color="#171D29"
          tile
        >
          <p class="mb-0 text-center text-button">{{ i.title }}</p>
          <div>
            <ul class="">
              <li v-for="j in i.messages" :key="j" class="changelog-item">
                {{ j }}
              </li>
            </ul>
          </div>
          <!-- <p class="pl-4 mb-0 text-button">2021-03-24</p>
          <ul class="text-button">
            <li class="changelog-item">Initial release</li>
          </ul> -->
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
export default {
  data: () => ({
    content: { title: "Help Page" },
    help: [
      {
        title: "Creating a deck",
        messages: [
          "Click the title box and give your deck a title. This should be no more than 30 characters.",
          "Click the description box and give your a deck a description on how to use it, what cards can be substituted etc. This should be no more than 900 characters.",
          "Click the Select Shikigami dropdown and add 4 Shikigami to your deck. You can type in this box to filter by name.",
          "Click the dropdown that appears next to each Shikigami and add 8 cards to your deck.",
        ],
      },
      {
        title: "Saving a deck",
        messages: [
          "When finished, double check everything is correct and click the Generate Sharing Link button and copy the link that appears above the box.",
          "If the sharing link does not appear, or there is an error, try reducing the length of your description a bit more. There is a character limit to the URL length that is generated for each deck.",
          "If the sharing link still doesn't work, click the Show Long URL button. This link will always work.",
        ],
      },
      {
        title: "Additional Information",
        messages: [
          "When you've generated a sharing link, you cannot change/edit the deck that the link points to.",
          "However you can edit/change any deck (even those generated by others), and generate a new sharing link when you're finished.",
          "The only way to save a deck is to generate a sharing link or a long URL. If you leave the page without generating a link and saving it, your deck will be lost. ",
          "You can generate a sharing link on a deck that isn't complete to save it.",
          "There is no limit to the number of sharing links you can have.",
        ],
      },
    ],
  }),
};
</script>

<style lang="sass" scoped></style>
